[tool.flit]
name = "my-pyhc-package"
version = "0.0.0"
description = "A package of my awesome Python code that will transform heliophysics forever."

license = "BDS-3"

authors = [
    "PyHC"
]

readme = "README.md"

repository = "https://github.com/sapols/my-pyhc-package/tree/main"

keywords = [
    "awesome",
    "heliophysics",
    "package"
]
